version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /works
      - type: volume
        source: node_modules
        target: /works/node_modules

volumes:
  node_modules: